"use client";

import { Captions, FileText, ShieldCheck, Download, Mic, Award } from "lucide-react";
import { motion } from "framer-motion";

const features = [
  {
    icon: Captions,
    title: "AI Captioning",
    description:
      "Timestamped, speaker-aware captions generated by Gemini AI. Verbatim accuracy with non-speech sounds labeled — WCAG 2.1 AA compliant out of the box.",
  },
  {
    icon: FileText,
    title: "Smart Transcripts",
    description:
      "Clean, readable full transcripts with grammar polished and speakers labeled. Timestamped for search, screen readers, and legal backup.",
  },
  {
    icon: Mic,
    title: "Audio Descriptions",
    description:
      "Automatically flags visual content — equations on a board, graphs, slide changes — and generates audio description text. The step most competitors skip entirely.",
  },
  {
    icon: ShieldCheck,
    title: "Compliance Scoring",
    description:
      "Every lecture is scored against a WCAG / Section 508 rubric with a per-element checklist and actionable fix suggestions — audit-ready on day one.",
  },
  {
    icon: Download,
    title: "All Export Formats",
    description:
      "SRT, VTT, TXT, and PDF. Canvas-ready ZIP packages. Download compliant files or post directly to your LMS — no reformatting needed.",
  },
  {
    icon: Award,
    title: "Compliance Certificate",
    description:
      "Download a branded certificate confirming WCAG 2.1 AA compliance for every lecture. Massive value for audits, accreditation, and legal protection.",
  },
];

const container = {
  hidden: {},
  show: { transition: { staggerChildren: 0.1 } },
};

const item = {
  hidden: { opacity: 0, y: 24 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" as const } },
};

export function Features() {
  return (
    <section id="features" className="py-24">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center max-w-2xl mx-auto mb-16"
        >
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4 font-display">
            Not just captions.{" "}
            <span className="gradient-text">The full package.</span>
          </h2>
          <p className="text-muted-foreground text-lg">
            Every deliverable auditors check for, every format your LMS needs,
            every step of the compliance process — handled automatically.
          </p>
        </motion.div>

        <motion.div
          variants={container}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true }}
          className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6"
        >
          {features.map((feature) => (
            <motion.div
              key={feature.title}
              variants={item}
              className="glass rounded-2xl p-6 hover:bg-foreground/[0.03] transition-colors group"
            >
              <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center mb-4 group-hover:from-primary/30 group-hover:to-primary/10 transition-colors">
                <feature.icon className="w-5 h-5 text-primary" />
              </div>
              <h3 className="text-base font-semibold mb-2">{feature.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
