"use client";

import { Captions, FileText, ShieldCheck, Download } from "lucide-react";
import { motion } from "framer-motion";

const features = [
  {
    icon: Captions,
    title: "AI Captioning",
    description:
      "Timestamped, speaker-aware captions generated by Gemini AI. Exported as .VTT and .SRT — WCAG 2.1 AA compliant out of the box.",
  },
  {
    icon: FileText,
    title: "Smart Transcripts",
    description:
      "Clean, readable transcripts with filler words removed, grammar polished, and speakers labeled. Ready for students with hearing disabilities.",
  },
  {
    icon: ShieldCheck,
    title: "Accessibility Scoring",
    description:
      "Every lecture is scored against a WCAG / Section 508 rubric with actionable fix suggestions — so you always know where you stand.",
  },
  {
    icon: Download,
    title: "One-Click Export",
    description:
      "VTT, SRT, TXT, and Canvas-ready ZIP packages. Download compliant files or post directly to your LMS in one click.",
  },
];

const container = {
  hidden: {},
  show: { transition: { staggerChildren: 0.1 } },
};

const item = {
  hidden: { opacity: 0, y: 24 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" as const } },
};

export function Features() {
  return (
    <section id="features" className="py-24">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center max-w-2xl mx-auto mb-16"
        >
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
            Everything you need for{" "}
            <span className="gradient-text">accessible lectures</span>
          </h2>
          <p className="text-muted-foreground text-lg">
            A complete AI-powered toolkit that turns any recording into a fully
            compliant, accessible learning resource.
          </p>
        </motion.div>

        <motion.div
          variants={container}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true }}
          className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6"
        >
          {features.map((feature) => (
            <motion.div
              key={feature.title}
              variants={item}
              className="glass rounded-2xl p-6 hover:bg-white/[0.06] transition-colors group"
            >
              <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center mb-4 group-hover:from-primary/30 group-hover:to-primary/10 transition-colors">
                <feature.icon className="w-5 h-5 text-primary" />
              </div>
              <h3 className="text-base font-semibold mb-2">{feature.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
