"""
LMS Export utilities for Canvas, Blackboard, and other learning management systems.

Canvas uses the IMS Common Cartridge format for imports.
For caption files, the simplest integration is via the Canvas media library
which accepts .vtt and .srt files directly.
"""

import json
import zipfile
import io
from app.services.caption_formatter import CaptionFormatter


class LMSExporter:
    """Export lecture accessibility assets in LMS-compatible formats."""

    def __init__(self):
        self.formatter = CaptionFormatter()

    def create_canvas_package(
        self,
        lecture_title: str,
        captions: list[dict],
        transcript_text: str,
        score_data: dict | None = None,
        use_cleaned: bool = True,
    ) -> bytes:
        """
        Create a ZIP package for Canvas import containing:
        - WebVTT captions (.vtt)
        - SRT captions (.srt)
        - Plain text transcript (.txt)
        - Accessibility report (.json)
        """
        buffer = io.BytesIO()
        safe_title = "".join(c if c.isalnum() or c in " -_" else "" for c in lecture_title).strip()

        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            vtt_content = self.formatter.to_vtt(captions, use_cleaned)
            zf.writestr(f"{safe_title}/captions.vtt", vtt_content)

            srt_content = self.formatter.to_srt(captions, use_cleaned)
            zf.writestr(f"{safe_title}/captions.srt", srt_content)

            zf.writestr(f"{safe_title}/transcript.txt", transcript_text)

            if score_data:
                report = {
                    "lecture": lecture_title,
                    "accessibility_score": score_data,
                    "standards": ["WCAG 2.1 AA", "Section 508", "ADA Title II"],
                    "generated_by": "AccessLecture",
                }
                zf.writestr(
                    f"{safe_title}/accessibility_report.json",
                    json.dumps(report, indent=2),
                )

            readme = (
                f"# {lecture_title} - Accessibility Package\n\n"
                f"Generated by AccessLecture\n\n"
                f"## Contents\n\n"
                f"- `captions.vtt` - WebVTT captions (for HTML5 video players)\n"
                f"- `captions.srt` - SRT subtitles (for VLC, YouTube, etc.)\n"
                f"- `transcript.txt` - Plain text transcript with speaker labels\n"
                f"- `accessibility_report.json` - Compliance scoring report\n\n"
                f"## Canvas Integration\n\n"
                f"1. Upload captions.vtt to your Canvas media library\n"
                f"2. Associate the VTT file with your lecture video\n"
                f"3. Upload transcript.txt as a page or file for students\n"
            )
            zf.writestr(f"{safe_title}/README.md", readme)

        buffer.seek(0)
        return buffer.read()
