import JSZip from "jszip";
import { toVtt, toSrt, toTxt } from "./caption-formatter";

export async function createCanvasPackage(
  lectureTitle: string,
  captions: Array<Record<string, unknown>>,
  transcriptText: string,
  scoreData?: Record<string, unknown> | null,
  useCleaned = true
): Promise<Buffer> {
  const safeTitle = lectureTitle.replace(/[^a-zA-Z0-9 _-]/g, "").trim();
  const zip = new JSZip();
  const folder = zip.folder(safeTitle)!;

  folder.file("captions.vtt", toVtt(captions, useCleaned));
  folder.file("captions.srt", toSrt(captions, useCleaned));
  folder.file("transcript.txt", transcriptText);

  if (scoreData) {
    const report = {
      lecture: lectureTitle,
      accessibility_score: scoreData,
      standards: ["WCAG 2.1 AA", "Section 508", "ADA Title II"],
      generated_by: "AccessLecture",
    };
    folder.file("accessibility_report.json", JSON.stringify(report, null, 2));
  }

  folder.file(
    "README.md",
    `# ${lectureTitle} - Accessibility Package\n\n` +
      `Generated by AccessLecture\n\n` +
      `## Contents\n\n` +
      `- \`captions.vtt\` - WebVTT captions (for HTML5 video players)\n` +
      `- \`captions.srt\` - SRT subtitles (for VLC, YouTube, etc.)\n` +
      `- \`transcript.txt\` - Plain text transcript with speaker labels\n` +
      `- \`accessibility_report.json\` - Compliance scoring report\n\n` +
      `## Canvas Integration\n\n` +
      `1. Upload captions.vtt to your Canvas media library\n` +
      `2. Associate the VTT file with your lecture video\n` +
      `3. Upload transcript.txt as a page or file for students\n`
  );

  const buf = await zip.generateAsync({ type: "nodebuffer" });
  return buf;
}
